site_name: "WebGrep - A Web page Grep-like extended and extensible tool"
repo_url: https://github.com/dhondta/webgrep
site_author: dhondta
docs_dir: doc
pages:
  - Introduction: index.md
  - Using WebGrep: usage.md
  - Extending WebGrep: create.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
use_directory_urls: false
markdown_extensions:
  - admonition
  - codehilite
